version: "3.9"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin

  spring_app:
    image: bilel98/devops-rattrapage:examen
    container_name: spring_app
    restart: on-failure
    ports:
      - 9090:9090
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: adminadmin
