version: "3.9"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
  spring_app:
    images: bilel98/devops-rattrapage:examen
    container_name: spring_app
    restart: on-failure
    ports:
      -9090:9090
    depends_on:
      - mysqldb
   environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/property?createDatabaseIfNotExist=true
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD:   
    
